### ISSUE TITLE
No text visible in Anki's dark mode

### ISSUE THREAD

**Issue by homocomputeris** [Ajatt-Tools/AnkiNoteTypes#15]
No text is visible when Anki's dark (manual or auto) mode is enabled. When the light mode is enabled, text is readable.

AnkiNoteTypes is [fbff39e](https://github.com/Ajatt-Tools/AnkiNoteTypes/commit/fbff39ef35c98e4178d089425884371523d8cbd8)

**Environment**

1) OS name  Arch
2) OS version 
3) Python version Python 3.10.2
3) Anki version Version ⁨2.1.50 (1871b576)⁩ Python 3.10.2 Qt 5.15.2 PyQt 5.15.6
4) Logs
5) Screenshots, if applicable
![Снимок экрана от 2022-02-20 19-32-07](https://user-images.githubusercontent.com/7422433/154853350-614dea7f-db58-4312-a802-e0216b1bdebf.png)

**Describe the bug**
No text is visible when Anki's dark mode is enabled

**To Reproduce**
1) Use AnkiNoteTypes
2) Turn on Dark mode
3) See no text

**Expected behavior**
See text.

**Comment by tatsumoto-ren** [comment]
There's probably something wrong with the CSS, and it prevents text from being visible.
